import { z } from "zod";
import { idSchema } from "@/lib/validation/cart";

/**
 * Checkout input (SEC-4, SEC-16, SEC-20).
 *
 * The client picks *which* address and *which* shipping rate. It never states
 * what anything costs: there is no subtotal, shipping, tax or total field to
 * send, so there is none to tamper with. The server recomputes the whole quote
 * from the database immediately before the order row is written (SEC-11).
 */

export const quoteRequestSchema = z
  .object({
    addressId: idSchema,
    /** Omitted on the first quote: the cheapest rate for the zone is used. */
    shippingRateId: idSchema.optional(),
  })
  .strict();

export const checkoutSchema = z
  .object({
    addressId: idSchema,
    shippingRateId: idSchema,
  })
  .strict();

/**
 * One key per checkout *attempt*, generated by the browser with
 * `crypto.randomUUID()`. Two submissions of the same attempt (a double-click,
 * a retry after a dropped response) carry the same key and collapse to one
 * order; a genuine second purchase carries a new one (SEC-20).
 */
export const idempotencyKeySchema = z
  .string()
  .trim()
  .min(16)
  .max(128)
  .regex(/^[A-Za-z0-9_-]+$/, "Malformed idempotency key.");

export type QuoteRequest = z.infer<typeof quoteRequestSchema>;
export type CheckoutInput = z.infer<typeof checkoutSchema>;
